/**
 * MIAMI DEVOUR — NPC VOICE PLAYBACK / REACTION FRAMEWORK  (spec section 4)
 *
 * This module decides WHO speaks, WHEN, and HOW LOUD. It does not synthesise
 * anything and it does not know what a hole is: the game calls `say()` with a
 * category ('notice', 'flee', 'police_warning', …) and a world position, and
 * everything else — cooldowns, concurrency, distance culling, subtitles,
 * ducking — happens in here.
 *
 * ---------------------------------------------------------------------------
 * THE DEFAULT STATE IS "NO AUDIO ASSETS"
 *
 * The ElevenLabs key lives server-side and the voice bank is generated by an
 * offline batch job (spec section 4, "generation workflow"). Until the owner
 * supplies a key there is no manifest and no .webm on disk — so CAPTIONS ONLY
 * is the *normal* path, not the error path. `load()` never throws, never
 * rejects, and a failed load leaves a fully functional, fully rate-limited
 * caption system behind. Everything below (cooldowns, concurrency, the burst
 * damper, distance culling) runs identically in both modes, which means the
 * chatter *rhythm* the designer tunes with captions is the rhythm players get
 * once the audio lands. That is the whole reason the limiter is not bolted to
 * the playback code.
 *
 * ---------------------------------------------------------------------------
 * SIGNAL FLOW  (audio mode only)
 *
 *   AudioBufferSource ─▶ per-line gain ─▶ StereoPanner ─▶ deps.destination
 *                                                          (the mixer's voice
 *                                                           bus — we never
 *                                                           touch audio.js)
 *
 * Ducking is *published*, not applied: `voice.duckAmount` is a 0..1 number the
 * mixer reads each frame and multiplies into its own ambience bus. Reaching
 * into audio.js's internal nodes from here would mean two owners for one
 * GainParam, and the loser of that race is always the ambience bed.
 *
 * ---------------------------------------------------------------------------
 * RATE LIMITING — the actual difficulty (spec: "Do not make every NPC scream
 * at once. Use cooldowns, distance checks, voice concurrency limits, and
 * weighted variation.")
 *
 * Six independent gates, cheapest first, because in a crowd scene `say()` is
 * called dozens of times per second and 95% of those calls must die before
 * they allocate anything:
 *
 *   1. DISTANCE      — an NPC outside the audible ring returns immediately.
 *                      No line selection, no allocation, no caption. This is
 *                      first because it is one hypot and it rejects most of a
 *                      panicking crowd.
 *   2. GLOBAL GAP    — MIN_START_GAP between any two line starts, so three
 *                      NPCs that trigger in the same frame become a staggered
 *                      exchange instead of a chord.
 *   3. CONCURRENCY   — hard cap of 3 (spec says 2–3). Never exceeded, not by
 *                      `force`, not by a CRITICAL police line: a high priority
 *                      line *evicts* a lower one rather than adding a fourth.
 *   4. BURST DAMPER  — token bucket, see BURST_* below.
 *   5. COOLDOWNS     — per voice (a cast may not chatter), per speaker (one
 *                      NPC may not chatter), per category (no wave of 'notice').
 *   6. PER-LINE      — folded into the weighted pick: a line used inside
 *                      LINE_COOLDOWN gets weight 0, and the last few lines used
 *                      get a heavy weight penalty, so the same joke does not
 *                      come back twice in a minute.
 *
 * ---------------------------------------------------------------------------
 * DEPENDENCIES
 *
 * Only `./voicelines.js` (the data file, imported as a namespace so a rename of
 * one of its exports cannot break the build) and nothing else. No three, no
 * config.js, no audio.js, no UI. The few world constants needed for panning are
 * mirrored from CAMERA in src/core/quality.js and are overridable via
 * `deps.camera` — see CAMERA_MIRROR for why they are copied rather than
 * imported.
 */

// Namespace import on purpose. A named import of a symbol the data file does
// not export is a hard build failure, and this module is written before that
// file is finished; `_adaptLibrary` probes the shape at runtime instead and
// falls back to a tiny built-in bank if it recognises nothing. Guessing an
// export name here is exactly the failure mode the house rules warn about.
import * as LINE_LIB from './voicelines.js';

/* ======================================================== tuning ======= */

/** Priority ladder. Higher wins evictions and unlocks the long-range paths. */
export const VOICE_PRIORITY = {
  /** Idle flavour. First thing dropped, never heard off-screen. */
  CHATTER: 0,
  /** A reaction to the player: notice, flee, near miss, prop eaten. */
  REACT: 1,
  /** Police warnings, event announcements. Audible anywhere, ducks ambience. */
  IMPORTANT: 2,
  /** Match-defining callouts. May evict anything below it. */
  CRITICAL: 3,
};

/**
 * Every number the balance pass will want to touch. Exported so the tuner and
 * the tests read the same values — a magic number duplicated in a test is a
 * test that passes after the tuning changes and proves nothing.
 */
export const VOICE_TUNING = {
  /** Spec: "no more than 2-3 spoken lines at once". 3, and it is a hard cap. */
  MAX_CONCURRENT: 3,

  /**
   * Minimum seconds between two line STARTS. 0.42 s ≈ the gap a human leaves
   * before answering: below ~0.3 s two lines read as one garbled event, above
   * ~0.6 s a crowd stops feeling like a crowd.
   */
  MIN_START_GAP: 0.42,

  /* --- cooldowns ----------------------------------------------------- */
  /** Per cast (voice profile). Longer than the longest line by ~2×. */
  VOICE_COOLDOWN: 5.0,
  /** Per individual NPC. One pedestrian gets one line per approach, roughly. */
  SPEAKER_COOLDOWN: 7.0,
  /** Per category — stops forty simultaneous 'flee's becoming a queue. */
  CATEGORY_COOLDOWN: 1.6,
  /** Per line id. A player hears ~25 lines a match; 14 s ≈ no near-repeats. */
  LINE_COOLDOWN: 14.0,

  /* --- burst damper ---------------------------------------------------- */
  /**
   * Token bucket. WHY a bucket and not just a cooldown: the moment the hole
   * turns a corner, forty pedestrians pass the distance check in the same
   * frame. A plain cooldown produces a metronome — one line, exactly every N
   * seconds, forever, which sounds like a machine. A bucket gives the honest
   * shape of a real crowd: a short flurry as everyone notices (4 lines inside
   * ~2 s), then a thinning-out to a sustained mutter.
   *
   * CAPACITY 4 = the flurry size. REFILL 0.55/s = one line per ~1.8 s
   * sustained, which is a little slower than the 3-slot concurrency cap can
   * drain, so the cap stops being the binding constraint after the flurry —
   * exactly the intent.
   */
  BURST_CAPACITY: 4,
  BURST_REFILL: 0.55,

  /* --- distance -------------------------------------------------------- */
  /**
   * Audible / caption ranges as multiples of the camera's ground half-width,
   * so they scale with the hole the way the framing does: a 40 m hole sees a
   * much wider slice of city, and its NPCs must be audible across it.
   * 2.0 ≈ a bit beyond the screen edge (a voice may precede its owner).
   * 1.25 ≈ on-screen only — captions for someone you cannot see are noise.
   */
  AUDIBLE_MULT: 2.0,
  CAPTION_MULT: 1.25,
  /** Floor for tiny holes, so a match still starts with audible neighbours. */
  MIN_AUDIBLE: 34,

  /* --- mixing ---------------------------------------------------------- */
  /** Ambience dip while an IMPORTANT+ line plays. Slight, per spec. */
  DUCK_AMOUNT: 0.18,
  /** Fast in so the first syllable is already clear, slow out so it breathes. */
  DUCK_ATTACK: 0.09,
  DUCK_RELEASE: 0.45,
  /** Attenuation floor for IMPORTANT+ lines: a dispatcher is never inaudible. */
  IMPORTANT_GAIN_FLOOR: 0.55,
  /** Panning is narrowed for important lines — clarity beats localisation. */
  IMPORTANT_SPREAD: 0.45,

  /* --- captions -------------------------------------------------------- */
  /**
   * Caption + slot-reservation duration estimate when the real length is unknown
   * (captions-only mode, or before the buffer has decoded). 0.34 s per word is
   * ~175 wpm — a touch slower than the excited delivery these lines get, which
   * biases the estimate long. Long is the safe direction: it under-fills the
   * concurrency cap rather than over-filling it.
   */
  CAPTION_PER_WORD: 0.34,
  CAPTION_MIN: 1.1,
  CAPTION_MAX: 5.0,

  /* --- variation -------------------------------------------------------- */
  /** How many recently spoken line ids are remembered per category. */
  RECENT_MEMORY: 6,
  /** Weight multiplier applied to a remembered line. Not 0: never say never. */
  RECENT_PENALTY: 0.12,

  /** Decoded buffers kept in memory. ~40 short lines ≈ a couple of MB. */
  BUFFER_CACHE: 96,

  /**
   * A handle whose source never reported `ended` is force-retired this many
   * seconds past its expected end. Without it, one missed `onended` (they do
   * get dropped when a context is suspended by a tab switch mid-line) leaks a
   * concurrency slot, and three leaks make the city silent for the rest of the
   * match with no error anywhere.
   */
  ZOMBIE_GRACE: 2.0,
};

/**
 * Mirrored from CAMERA in src/core/quality.js (PITCH/YAW/DIST_BASE/DIST_PER_R).
 * Copied rather than imported so this module stays importable by a plain node
 * test with no bundler and no three; `deps.camera` overrides it if the camera
 * rig is ever re-tuned. Verified against src/core/quality.js:557 — YAW -35°,
 * DIST_BASE 44, DIST_PER_R 5.6 — and the projection below is the same one
 * audio.js `_pan()` uses, so a voice and a swallow at the same spot land in the
 * same place in the stereo field.
 */
const CAMERA_MIRROR = { YAW: -35, DIST_BASE: 44, DIST_PER_R: 5.6 };

/**
 * Absolute last-resort line bank. Used only when `./voicelines.js` exports
 * nothing this module recognises — which should never ship, but a silent city
 * with a console warning beats a crash, and it keeps `__selftest` honest even
 * if the data file is mid-edit by another agent.
 */
const EMERGENCY_LINES = {
  notice: ['Uh... is that a sinkhole?'],
  flee: ['Nope, nope, nope!'],
};

/* ======================================================== helpers ====== */

const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);

/** Stable, allocation-free string hash — used to give an id to a bare line. */
function hash32(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(36);
}

/** Speech length estimate from the text alone. See CAPTION_PER_WORD. */
function estimateSeconds(text, T) {
  const words = String(text || '').trim().split(/\s+/).filter(Boolean).length || 1;
  return clamp(0.55 + words * T.CAPTION_PER_WORD, T.CAPTION_MIN, T.CAPTION_MAX);
}

/**
 * Bind the DOCUMENTED api of ./voicelines.js. Read from that file, not guessed
 * (its shape is not what a first guess would produce, and a wrong guess here
 * fails silently — the game would run on the two-line emergency bank with one
 * console warning):
 *
 *   CATEGORIES            frozen string[] of category keys
 *   linesFor(cat)         frozen array of { id, cast, text, category, weight,
 *                         cooldown } — SHARED and frozen, never mutate it
 *   CAST                  ARRAY of { id, displayName, role, blurb,
 *                         voiceDirection, color, cooldown }
 *   CATEGORY_META[cat]    { label, defaultCooldown, priority }
 *
 * Note `LINES` is category → castId → lines (nested), which is why this binds
 * `linesFor()` instead: that function is the file's own flattening.
 *
 * The data file owns the cooldowns (per line, per voice) and the priority; this
 * module owns the clock. That split is stated in voicelines.js's own header
 * ("cooldown enforcement stays the caller's job"), so the numbers below come
 * from the corpus and only fall back to VOICE_TUNING when a field is absent.
 *
 * @returns {{categories: Map, casts: Map, meta: Map, count: number}|null}
 *   null when `lib` is not that module (then the shape prober takes over).
 */
function bindDocumentedApi(lib) {
  if (!lib || typeof lib.linesFor !== 'function' || !Array.isArray(lib.CATEGORIES)) return null;

  const categories = new Map();
  const casts = new Map();
  const meta = new Map();
  let count = 0;

  for (const cat of lib.CATEGORIES) {
    const rows = lib.linesFor(cat);
    if (!Array.isArray(rows) || rows.length === 0) continue;
    // Copy into our own objects. The source arrays are frozen and shared with
    // the offline generator; adding so much as an index to them would throw.
    const list = rows.map((r, i) => ({
      id: String(r.id),
      text: String(r.text),
      cast: r.cast || null,
      category: cat,
      weight: typeof r.weight === 'number' && r.weight > 0 ? r.weight : 1,
      // Per-line lockout, in seconds, straight from the corpus. The rare comic
      // lines carry 150 s+ here; that is the whole point of them being rare.
      cooldown: typeof r.cooldown === 'number' && r.cooldown > 0 ? r.cooldown : null,
      priority: null,
      index: i,
    }));
    categories.set(cat, list);
    count += list.length;

    const m = lib.CATEGORY_META && lib.CATEGORY_META[cat];
    if (m) {
      meta.set(cat, {
        label: m.label || cat,
        // Their scale is 1..4 (1 = flavour, 4 = police/storm/heat). Ours is
        // 0..3. Same ordering, one offset — mapped rather than reinterpreted so
        // that a 'notice' does not silently become an IMPORTANT line that ducks
        // the music and is audible across the entire map.
        priority: clamp((m.priority | 0) - 1, VOICE_PRIORITY.CHATTER, VOICE_PRIORITY.CRITICAL),
      });
    }
  }
  if (count === 0) return null;

  const castRows = Array.isArray(lib.CAST) ? lib.CAST : [];
  for (const c of castRows) {
    if (!c || !c.id) continue;
    casts.set(String(c.id), {
      id: String(c.id),
      name: String(c.displayName || c.name || c.id),
      // Carried into the caption so the HUD can colour-code the speaker —
      // alongside the name, never instead of it (voicelines.js's own
      // accessibility rule, and section 6 of the spec).
      color: c.color || null,
      role: c.role || null,
      // "seconds before THIS VOICE speaks again, at all, anywhere" — the
      // corpus's words. That is exactly this module's per-voice cooldown.
      cooldown: typeof c.cooldown === 'number' && c.cooldown > 0 ? c.cooldown : null,
      gain: typeof c.gain === 'number' ? clamp(c.gain, 0, 2) : 1,
    });
  }

  return { categories, casts, meta, count };
}

/**
 * Turn whatever `./voicelines.js` exports into { categories, casts }.
 *
 * The data file is written by a different pass and its exact export names are
 * not contracted, so this probes structure instead of names. Accepted shapes:
 *
 *   { notice: ['line', ...], flee: [...] }                  category → strings
 *   { notice: [{ id, text, cast, weight, priority }] }       category → entries
 *   [ { category: 'notice', text: '...' }, ... ]             flat array
 *   { LINES: <any of the above>, CAST: { id: {name} } }      named containers
 *
 * An entry's audio asset id is, in order: `.asset` / `.assetId` / `.id`, else
 * `<category>-<hash of text>`. That id is the key looked up in the generated
 * manifest, so the offline generator and this file must agree on it — which is
 * why the fallback is a hash of the text and not an array index (an index
 * shifts the moment someone inserts a line, silently re-pointing every asset).
 */
function adaptLibrary(src) {
  const categories = new Map();
  const casts = new Map();
  const ids = new Map();          // category → Set of ids already taken
  if (!src || typeof src !== 'object') return { categories, casts, count: 0 };

  const addEntry = (category, raw, i) => {
    if (raw == null) return;
    const o = typeof raw === 'string' ? { text: raw } : raw;
    const text = o.text ?? o.line ?? o.caption ?? (typeof raw === 'string' ? raw : null);
    if (!text || typeof text !== 'string') return;
    const cast = o.cast ?? o.castId ?? o.voice ?? o.voiceId ?? null;
    const id = String(o.asset ?? o.assetId ?? o.id ?? `${category}-${hash32(text)}`);
    let list = categories.get(category);
    if (!list) { list = []; categories.set(category, list); ids.set(category, new Set()); }
    // `export const LINES = {...}; export default LINES;` is the single most
    // likely shape of the data file, and it presents the same table twice.
    // Without this, every line would be registered twice — harmless for
    // weighting but it doubles the per-line cooldown map and makes the
    // "distinct lines" diagnostics lie.
    const taken = ids.get(category);
    if (taken.has(id)) return;
    taken.add(id);
    list.push({
      id,
      text,
      cast,
      category,
      weight: typeof o.weight === 'number' && o.weight > 0 ? o.weight : 1,
      // A data file may pin a line as always-important (dispatcher lines).
      priority: typeof o.priority === 'number' ? o.priority : null,
      tags: o.tags || null,
      index: i,
    });
  };

  /** A "category map" is an object whose values are arrays of lines. */
  const eatCategoryMap = (obj) => {
    let took = 0;
    for (const [k, v] of Object.entries(obj)) {
      /* TWO-LEVEL SHAPE: obj[category][castId] = [...], which is exactly how
         voicelines.js exposes its `LINES` export — a line belongs to both a
         category and a character. A one-level prober sees an object where it
         wants an array, matches nothing, and drops the entire corpus into the
         emergency bank with a single console warning. The real library is
         bound by `bindDocumentedApi` before this ever runs; this branch is for
         stubs and per-mode banks that copy the same nesting. */
      if (v && typeof v === 'object' && !Array.isArray(v)) {
        let inner = 0;
        for (const [castId, list] of Object.entries(v)) {
          if (!Array.isArray(list) || !list.length) continue;
          list.forEach((e, i) => addEntry(
            k,
            // Carry the cast down from the key when the entry omits it, so
            // per-voice cooldowns and voice assignment still work.
            (e && typeof e === 'object') ? { cast: castId, ...e } : { cast: castId, text: e },
            i
          ));
          inner++;
        }
        if (inner) { took++; continue; }
      }
      if (!Array.isArray(v) || v.length === 0) continue;
      const first = v[0];
      if (typeof first !== 'string' && (typeof first !== 'object' || first === null)) continue;
      v.forEach((e, i) => addEntry(k, e, i));
      took++;
    }
    return took;
  };

  /** A flat array of entries that name their own category. */
  const eatFlatArray = (arr) => {
    let took = 0;
    for (let i = 0; i < arr.length; i++) {
      const e = arr[i];
      if (!e || typeof e !== 'object') continue;
      const cat = e.category ?? e.cat ?? e.kind;
      if (!cat) continue;
      addEntry(String(cat), e, i);
      took++;
    }
    return took;
  };

  const addCast = (key, v) => {
    const name = v.displayName ?? v.name ?? v.label ?? v.display;
    if (!name && !v.description && !v.desc && !v.voiceDirection) return 0;
    const id = String(v.id ?? key);
    casts.set(id, {
      id,
      name: String(name || id),
      color: v.color || null,
      role: v.role || null,
      cooldown: typeof v.cooldown === 'number' && v.cooldown > 0 ? v.cooldown : null,
      // Per-cast trim: an excited teen and a calm dispatcher are not level.
      gain: typeof v.gain === 'number' ? clamp(v.gain, 0, 2) : 1,
      priority: typeof v.priority === 'number' ? v.priority : null,
    });
    return 1;
  };

  /** Cast profiles keyed by id: { mina: { name, … }, … } */
  const eatCasts = (obj) => {
    let took = 0;
    for (const [k, v] of Object.entries(obj)) {
      if (!v || typeof v !== 'object' || Array.isArray(v)) continue;
      // A category-metadata table ({ label, defaultCooldown, priority }) looks
      // enough like a cast table to be swallowed by the `label` test, and then
      // every category name becomes a "character". `defaultCooldown` is the
      // tell — it exists on meta and on nothing else.
      if (v.defaultCooldown !== undefined) continue;
      took += addCast(k, v);
    }
    return took;
  };

  /** Cast profiles as an ARRAY of self-identifying objects — voicelines.js's
   *  own `CAST` shape, and the one a keyed-object prober silently ignores. */
  const eatCastArray = (arr) => {
    let took = 0;
    for (const v of arr) {
      if (!v || typeof v !== 'object' || !v.id) continue;
      if (v.category ?? v.cat ?? v.kind) continue;     // that is a line, not a cast
      took += addCast(v.id, v);
    }
    return took;
  };

  // Probe the module namespace itself first (it may BE the category map), then
  // every exported object/array. Functions are skipped: a namespace always has
  // some, and calling one to see what it returns would be a real side effect.
  const candidates = [src, ...Object.values(src)];
  const seen = new Set();
  for (const c of candidates) {
    if (!c || typeof c === 'function') continue;
    if (typeof c !== 'object') continue;
    if (seen.has(c)) continue;       // default export aliasing a named one
    seen.add(c);
    // An array is either lines that name their category, or a cast list. Both
    // are tried; each ignores what the other owns.
    if (Array.isArray(c)) { eatFlatArray(c); eatCastArray(c); continue; }
    // Cast tables and line tables are told apart by their VALUES: arrays mean
    // lines, plain named objects mean casts. A file can export both.
    eatCategoryMap(c);
    eatCasts(c);
  }

  let count = 0;
  for (const list of categories.values()) count += list.length;
  return { categories, casts, count };
}

/* ==================================================== VoiceSystem ====== */

export class VoiceSystem {
  /**
   * @param {object} deps
   * @param {BaseAudioContext} [deps.audioCtx]  shared context. Omit → captions
   *   only. Pass the SAME context audio.js unlocked; a second AudioContext is
   *   a second hardware stream and the two drift apart audibly.
   * @param {AudioNode} [deps.destination]  the mixer's voice bus. Omit and we
   *   use ctx.destination, which bypasses master volume — acceptable for a
   *   test, wrong for the game.
   * @param {function} [deps.rng]  seeded rng (src/core/rng.js style: a callable
   *   returning 0..1). Falls back to Math.random.
   * @param {function} [deps.getListener]  () => {x, z, radius} | null. Called
   *   once per `say()`; return null while there is no player (menus) and every
   *   positional line is culled automatically.
   * @param {object} [deps.lines]  override for the imported line library —
   *   used by tests, and by any caller that wants a per-mode line bank.
   * @param {object} [deps.camera]  { YAW, DIST_BASE, DIST_PER_R } override.
   * @param {function} [deps.onCaption]  see `onCaption`.
   */
  constructor(deps = {}) {
    this.ctx = deps.audioCtx || null;
    this.destination = deps.destination || null;
    this.rng = typeof deps.rng === 'function' ? deps.rng : Math.random;
    this.getListener = typeof deps.getListener === 'function' ? deps.getListener : () => null;
    this.camera = { ...CAMERA_MIRROR, ...(deps.camera || {}) };
    this.T = { ...VOICE_TUNING, ...(deps.tuning || {}) };

    /**
     * HUD hook. `onCaption({ id, text, castName, category, priority, ttl,
     * distance, spoken })` — assign a function and subtitles appear; leave it
     * null and this module is silent about UI entirely. `onCaptionClear()` is
     * called by `stopAll()` so the HUD can wipe stale lines on a restart.
     */
    this.onCaption = typeof deps.onCaption === 'function' ? deps.onCaption : null;
    this.onCaptionClear = typeof deps.onCaptionClear === 'function' ? deps.onCaptionClear : null;

    /* --- line data ---------------------------------------------------- */
    // Two ways in, in order of trust: the documented api of voicelines.js, or
    // structural probing for anything else (a test stub, a per-mode bank).
    const src = deps.lines || LINE_LIB;
    const bound = bindDocumentedApi(src);
    this.categoryMeta = bound ? bound.meta : new Map();
    const adapted = bound || adaptLibrary(src);
    if (adapted.count === 0) {
      // One warning, once. A per-call warning in a crowd scene is its own
      // performance bug and buries the message it is trying to deliver.
      if (typeof console !== 'undefined' && console.warn) {
        console.warn('[voice] no usable lines in ./voicelines.js — using the emergency bank');
      }
      const fb = adaptLibrary(EMERGENCY_LINES);
      this.lines = fb.categories;
      this.casts = fb.casts;
      this.usingFallbackLines = true;
    } else {
      this.lines = adapted.categories;
      this.casts = adapted.casts;
      this.usingFallbackLines = false;
    }

    /* --- assets ------------------------------------------------------- */
    /** 'captions' until a manifest with at least one entry has loaded. */
    this.mode = 'captions';
    this.manifest = new Map();     // asset id → absolute url
    this._buffers = new Map();     // asset id → AudioBuffer | 'missing' | Promise

    /* --- mixer state --------------------------------------------------- */
    this._volume = 0.9;
    this._muted = false;
    this.subtitles = true;
    this._duck = 0;

    /* --- scheduling state ---------------------------------------------- */
    /**
     * Internal clock, advanced ONLY by `update(dt)`. Deliberately not
     * ctx.currentTime: cooldowns must tick with the simulation, must be
     * testable without WebAudio, and must freeze when the game is paused —
     * a paused game that silently burns off every cooldown produces a wall of
     * chatter the instant it resumes.
     */
    this.time = 0;
    this._active = [];             // live handles, length <= MAX_CONCURRENT
    this._lastStart = -1e6;
    this._tokens = this.T.BURST_CAPACITY;
    this._cdVoice = new Map();     // castId    → time free
    this._cdSpeaker = new Map();   // speakerId → time free
    this._cdCategory = new Map();  // category  → time free
    this._cdLine = new Map();      // line id   → time free
    this._recent = new Map();      // category  → array of recent line ids

    /**
     * Bumped by `stopAll()`. Every async continuation (manifest fetch, buffer
     * decode, playback start) captures the value and bails if it changed. This
     * is the ONLY thing standing between a match restart and a line from the
     * previous match starting two seconds into the new one — the fetch was
     * already in flight when the world was torn down, and nothing else in the
     * chain knows the match is gone.
     */
    this._gen = 0;

    this.stats = {
      said: 0, played: 0, captions: 0,
      cutDistance: 0, cutGap: 0, cutCap: 0, cutBurst: 0, cutCooldown: 0, cutNoLine: 0,
      evicted: 0, loadFails: 0,
    };
  }

  /* ------------------------------------------------------------ assets -- */

  /**
   * Fetch the generated voice manifest. NEVER throws and NEVER rejects.
   *
   * THE SHIPPING SHAPE, verified against tools/generate-voices.mjs (it writes
   * public/audio/voice/manifest.json, default url base '/audio/voice'):
   *
   *   { version, generated, pipeline: {...}, counts: {...},
   *     lines: { "<lineId>": { "url": "/audio/voice/x.mp3", "ms": 1420,
   *                            "cast": "mina-sol" } } }
   *
   * Note `ms`, not seconds — reading only `seconds` there would silently fall
   * back to the word-count estimate for every line and put captions out of step
   * with the audio. These are also accepted, for a hand-written pack:
   *   { "assets": { "<lineId>": "xyz.webm" } }
   *   { "lines":  { "<lineId>": { "url": "...", "seconds": 1.4 } } }
   *   { "<lineId>": "xyz.webm" }
   * URL RULE, and the generator must match it: a relative url resolves against
   * the MANIFEST's url by ordinary URL semantics. A manifest at `/vo/x.json`
   * listing `a.webm` means `/vo/a.webm`; listing `vo/a.webm` means
   * `/vo/vo/a.webm`. Urls starting with `/`, `http:`, `data:` or `blob:` are
   * taken verbatim. Resolving against the page instead would break the moment
   * the build moves the pack under a hashed directory, and a naive string join
   * would double the prefix — which is precisely the bug this rule prevents.
   *
   * @returns {Promise<boolean>} true = audio mode, false = captions only.
   */
  async load(manifestUrl) {
    const gen = this._gen;
    this.mode = 'captions';
    this.manifest.clear();
    // Drop the decoded/negative cache with the manifest. A 'missing' marker is
    // permanent by design (no request storms), so keeping it across a reload
    // would mean the voice pack generated *after* the first failed load can
    // never be heard — the game would sit in captions-only mode forever with
    // a perfectly good manifest in hand.
    this._buffers.clear();
    if (this._durations) this._durations.clear();

    if (!manifestUrl || typeof fetch !== 'function') return false;
    // Remembered so say() can retry. A pack that failed once — a slow first
    // paint, a fetch racing the service worker — must not condemn the whole
    // session to captions with 111 playable files sitting on disk.
    this._manifestUrl = manifestUrl;
    try {
      const res = await fetch(manifestUrl, { cache: 'force-cache' });
      // A dev server answers a missing file with a 200 + index.html. Checking
      // ok is not enough; the JSON parse below is the real guard, and it is
      // inside the try for exactly that reason.
      if (!res || !res.ok) throw new Error(`HTTP ${res && res.status}`);
      const json = await res.json();
      if (gen !== this._gen) return false;    // stopAll() happened mid-fetch

      /* `entries` accepted too: the first generated manifest used that key and
         the loader silently registered ZERO assets — it fell through to the
         top-level object, found no `.url` on `generated` or `entries`, and
         reported a perfectly successful load of an empty pack. The game sat in
         captions-only mode with 111 playable files on disk. Accept the obvious
         synonyms rather than make the manifest guess. */
      const table = (json && (json.assets || json.entries || json.lines || json.voices)) || json;
      if (!table || typeof table !== 'object') throw new Error('shape');

      const base = typeof URL === 'function' ? manifestUrl : null;
      for (const [id, v] of Object.entries(table)) {
        const raw = typeof v === 'string' ? v : v && (v.url || v.file || v.path);
        if (!raw || typeof raw !== 'string') continue;
        let url = raw;
        if (base && !/^(https?:|data:|blob:|\/)/.test(raw)) {
          try { url = new URL(raw, new URL(base, globalThis.location?.href || 'http://x/')).href; }
          catch { url = raw; }
        }
        this.manifest.set(String(id), url);
        // `ms` is what the generator writes (exact when it had ffprobe);
        // `seconds` is accepted for a hand-rolled manifest.
        if (v && typeof v === 'object') {
          const secs = typeof v.seconds === 'number' ? v.seconds
            : typeof v.ms === 'number' ? v.ms / 1000 : 0;
          if (secs > 0) this._seconds(String(id), secs);
        }
      }
      if (this.manifest.size === 0) throw new Error('empty');

      // No AudioContext means we can hold the manifest but still cannot play:
      // report captions so the caller's UI does not promise audio it lacks.
      this.mode = this.ctx ? 'audio' : 'captions';
      return this.mode === 'audio';
    } catch (err) {
      // Deliberately quiet at info level: "no voice pack" is the normal state
      // of this game until someone runs the generator. An error() here would
      // train everyone to ignore the console.
      this.stats.loadFails++;
      if (typeof console !== 'undefined' && console.info) {
        console.info('[voice] no voice pack (captions only):', err && err.message);
      }
      this.manifest.clear();
      this.mode = 'captions';
      return false;
    }
  }

  /**
   * Hand over the AudioContext once it exists. REQUIRED in the real game and
   * easy to miss: browsers only allow a context after a user gesture, so the
   * boot sequence is `new VoiceSystem()` → `load(manifest)` (no context yet,
   * so it parks in caption mode) → first click → `audio.unlock()` →
   * `attachContext(audio.ctx, voiceBus)`. Without this call the voice pack
   * downloads perfectly and is never heard, with nothing in the console to
   * say why.
   */
  attachContext(ctx, destination = null) {
    if (!ctx) return this;
    this.ctx = ctx;
    if (destination) this.destination = destination;
    if (this.manifest.size > 0) {
      // Entries fetched (or refused) while there was no context are cached as
      // 'missing'; that verdict is stale now.
      this._buffers.clear();
      this.mode = 'audio';
    }
    return this;
  }

  /** Manifest-declared durations, so the slot reservation is exact pre-decode. */
  _seconds(id, s) {
    if (!this._durations) this._durations = new Map();
    if (s > 0) this._durations.set(id, s);
    return this._durations.get(id);
  }

  /**
   * Decoded buffer for an asset, or null. Caches negatives as 'missing' so a
   * 404 on a popular line does not re-fetch on every reaction for a whole
   * match (that turns one missing file into a request storm).
   */
  async _buffer(id) {
    const hit = this._buffers.get(id);
    if (hit === 'missing') return null;
    if (hit) return hit;              // AudioBuffer, or the in-flight Promise

    const url = this.manifest.get(id);
    if (!url || !this.ctx) { this._buffers.set(id, 'missing'); return null; }

    const p = (async () => {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const bytes = await res.arrayBuffer();
      // Promise form is not universal (older Safari is callback-only), and the
      // callback form rejects nothing — hence the manual wrapper.
      const buf = await new Promise((resolve, reject) => {
        const out = this.ctx.decodeAudioData(bytes, resolve, reject);
        if (out && typeof out.then === 'function') out.then(resolve, reject);
      });
      return buf;
    })();

    this._buffers.set(id, p);
    try {
      const buf = await p;
      // Crude cap, oldest-inserted first: Map preserves insertion order, and a
      // true LRU here would cost more bookkeeping than the memory it saves.
      if (this._buffers.size > this.T.BUFFER_CACHE) {
        const first = this._buffers.keys().next().value;
        if (first !== id) this._buffers.delete(first);
      }
      this._buffers.set(id, buf);
      return buf;
    } catch (err) {
      this.stats.loadFails++;
      this._buffers.set(id, 'missing');
      return null;
    }
  }

  /* -------------------------------------------------------------- mix --- */

  setVolume(v) { this._volume = clamp(Number(v) || 0, 0, 1); return this; }
  getVolume() { return this._volume; }

  /**
   * Muting kills AUDIO, not captions: subtitles are the accessibility path and
   * a deaf player muting voices must keep reading them. It also does not touch
   * the rate limiter — the chatter cadence stays identical muted or not, so a
   * player toggling voices mid-match does not get a burst on unmute.
   */
  setMuted(m) {
    this._muted = !!m;
    if (this._muted) this._stopSources();
    return this;
  }
  isMuted() { return this._muted; }

  setSubtitles(on) { this.subtitles = !!on; return this; }

  /**
   * 0..DUCK_AMOUNT. The mixer multiplies its ambience (and optionally music)
   * bus by (1 - duckAmount) each frame. A getter, not a node: see the header.
   */
  get duckAmount() { return this._duck; }

  /** Live line count. Never exceeds MAX_CONCURRENT — see `__selftest`. */
  get activeCount() { return this._active.length; }

  /** True when a voice pack loaded AND a context exists to play it. */
  get hasAudio() { return this.mode === 'audio' && !!this.ctx && !this._muted; }

  /* -------------------------------------------------------- geometry --- */

  /**
   * Camera ground half-width — the same expression audio.js `_pan()` uses, so
   * "just off screen" means the same distance to both systems.
   */
  _frameHalf(radius) {
    const r = typeof radius === 'number' && isFinite(radius) ? radius : 1;
    return Math.max(14, (this.camera.DIST_BASE + r * this.camera.DIST_PER_R) * 0.5);
  }

  /**
   * @returns {{d:number, half:number, gain:number, pan:number}} placement for a
   * source at (x,z) relative to the current listener.
   */
  _place(x, z, listener, spread) {
    const half = this._frameHalf(listener ? listener.radius : 1);
    const dx = x - listener.x, dz = z - listener.z;
    const d = Math.hypot(dx, dz);
    const yaw = (this.camera.YAW * Math.PI) / 180;
    // Screen-right in world XZ for the fixed camera yaw (engine.js convention).
    const pan = clamp((dx * Math.cos(yaw) - dz * Math.sin(yaw)) / half, -1, 1) * 0.8 * spread;
    // Linear-ish rolloff to zero at the audible edge. Inverse-square was tried
    // in the sfx bus and makes speech unintelligible long before it is quiet;
    // dialogue wants a flatter curve with a hard cut.
    const gain = clamp(1.1 - d / (half * this.T.AUDIBLE_MULT), 0, 1);
    return { d, half, gain, pan };
  }

  /* --------------------------------------------------------- speaking --- */

  /**
   * Request a line. Cheap to call every frame from every NPC — that is the
   * design point; the gates below reject most calls before allocating.
   *
   * @param {string} category  'notice' | 'flee' | 'near_miss' | … whatever the
   *   line file defines. An unknown category is a no-op (returns null), never
   *   an error: content and code ship on different days.
   * @param {object} [opts]
   * @param {number} [opts.x] @param {number} [opts.z]  world position. Omit for
   *   a non-diegetic line (dispatcher, announcer) — it plays centred, full
   *   gain, and skips the distance gate entirely.
   * @param {string} [opts.castId]  pin the voice profile (a given NPC should
   *   always use the same one — pass the cast you assigned it at spawn).
   * @param {string} [opts.speakerId]  pin the individual NPC, for its own
   *   cooldown. Defaults to castId.
   * @param {number} [opts.priority]  VOICE_PRIORITY.*, default REACT.
   * @param {string} [opts.lineId]  force a specific line (scripted beats).
   * @param {boolean} [opts.force]  bypass the gap, the burst damper, every
   *   cooldown and the distance cut — for scripted beats the designer wants
   *   heard. It does NOT bypass the concurrency cap: a forced line evicts a
   *   strictly lower-priority one or is dropped. No flag anywhere in this
   *   module can produce a 4th simultaneous voice.
   * @returns {object|null} the handle, or null if suppressed.
   */
  /**
   * One retry of the manifest, on demand.
   *
   * Called from say() when we are still in captions mode but a URL is known.
   * Guarded by a flag AND by "is a load already in flight", so a busy scene
   * cannot turn a miss into a request storm.
   */
  _retryPack() {
    if (this.mode === 'audio' || this._packRetried || this._packLoading) return;
    if (!this._manifestUrl) return;
    this._packRetried = true;
    this._packLoading = true;
    Promise.resolve(this.load(this._manifestUrl))
      .catch(() => {})
      .then(() => { this._packLoading = false; });
  }

  say(category, opts = {}) {
    // Cheap, once, and only while it would change anything.
    if (this.mode !== 'audio') this._retryPack();
    const T = this.T;
    const cat = String(category || '');
    const list = this.lines.get(cat);
    if (!list || list.length === 0) { this.stats.cutNoLine++; return null; }

    // Priority comes from the corpus unless the caller pins it: CATEGORY_META
    // already ranks 'notice' below 'policeWarning', and duplicating that
    // judgement at every call site is how the two drift apart.
    const catMeta = this.categoryMeta.get(cat);
    const priority = typeof opts.priority === 'number'
      ? opts.priority
      : (catMeta && catMeta.priority != null ? catMeta.priority : VOICE_PRIORITY.REACT);
    const positional = typeof opts.x === 'number' && typeof opts.z === 'number';
    const force = !!opts.force;

    /* --- gate 1: distance (cheapest, rejects most of a crowd) --------- */
    let place = null, dist = 0;
    if (positional) {
      const listener = this.getListener();
      if (!listener || typeof listener.x !== 'number') {
        // No listener = no match running. Only non-positional important lines
        // (menu/announcer) have any business speaking here.
        this.stats.cutDistance++;
        return null;
      }
      place = this._place(opts.x, opts.z, listener, priority >= VOICE_PRIORITY.IMPORTANT
        ? T.IMPORTANT_SPREAD : 1);
      dist = place.d;
      const audible = Math.max(T.MIN_AUDIBLE, place.half * T.AUDIBLE_MULT);
      if (dist > audible && priority < VOICE_PRIORITY.IMPORTANT && !force) {
        // Spec: "Far-away NPCs use simple reactions/no sound for performance."
        // Returning here means no line pick, no caption, no node, no cooldown
        // burn — a distant crowd costs one hypot per NPC per attempt.
        this.stats.cutDistance++;
        return null;
      }
      // Important lines are heard everywhere but never at full localisation.
      if (priority >= VOICE_PRIORITY.IMPORTANT) {
        place.gain = Math.max(place.gain, T.IMPORTANT_GAIN_FLOOR);
      }
    }

    /* --- gate 2: global start gap ------------------------------------- */
    if (!force && this.time - this._lastStart < T.MIN_START_GAP) { this.stats.cutGap++; return null; }

    /* --- gate 3: concurrency (hard) ------------------------------------ */
    // Resolved BEFORE cooldowns are burned so a rejected line leaves no trace.
    let evict = null;
    if (this._active.length >= T.MAX_CONCURRENT) {
      evict = this._evictionTarget(priority);
      if (!evict) { this.stats.cutCap++; return null; }
    }

    /* --- gate 4: burst damper ------------------------------------------ */
    if (!force && this._tokens < 1) { this.stats.cutBurst++; return null; }

    /* --- gate 5: cooldowns --------------------------------------------- */
    if (!force) {
      if ((this._cdCategory.get(cat) || 0) > this.time) { this.stats.cutCooldown++; return null; }
      const sid = opts.speakerId || opts.castId;
      if (sid && (this._cdSpeaker.get(sid) || 0) > this.time) { this.stats.cutCooldown++; return null; }
      if (opts.castId && (this._cdVoice.get(opts.castId) || 0) > this.time) {
        this.stats.cutCooldown++; return null;
      }
    }

    /* --- gate 6: line pick (per-line cooldown + anti-repeat) ----------- */
    const entry = opts.lineId
      ? list.find((e) => e.id === opts.lineId) || null
      : this._pick(cat, list, opts.castId, force);
    if (!entry) { this.stats.cutNoLine++; return null; }

    const castId = opts.castId || entry.cast || null;
    // A cast picked from the line itself still has to respect its own cooldown
    // — otherwise pinning casts in the data file quietly disables gate 5.
    if (!force && castId && !opts.castId && (this._cdVoice.get(castId) || 0) > this.time) {
      this.stats.cutCooldown++;
      return null;
    }

    const effPriority = entry.priority != null ? Math.max(priority, entry.priority) : priority;

    /* --- commit -------------------------------------------------------- */
    if (evict) this._retire(evict, true);

    const cast = castId ? this.casts.get(castId) : null;
    // Prefer the length the generator measured; the word-count estimate is
    // only a stand-in for "we have not decoded this yet / there is no audio".
    const declared = this._durations ? this._durations.get(entry.id) : 0;
    const ttl = declared > 0 ? declared : estimateSeconds(entry.text, T);

    const handle = {
      id: entry.id,
      category: cat,
      text: entry.text,
      castId,
      castName: cast ? cast.name : null,
      color: cast ? cast.color || null : null,
      priority: effPriority,
      x: positional ? opts.x : null,
      z: positional ? opts.z : null,
      distance: dist,
      startedAt: this.time,
      endsAt: this.time + ttl,
      ttl,
      gen: this._gen,
      src: null,
      nodes: null,
      spoken: false,
    };

    this._active.push(handle);
    this._lastStart = this.time;
    if (!force) this._tokens -= 1;

    // The corpus is the authority on how rare a line and how talkative a
    // character are: a line carries its own lockout (the rare comic ones sit at
    // 150 s+) and a cast carries "seconds before this voice speaks again, at
    // all, anywhere". VOICE_TUNING only fills in what the data omits, so
    // rebalancing chatter is a content edit, not a code edit.
    this._cdCategory.set(cat, this.time + T.CATEGORY_COOLDOWN);
    this._cdLine.set(entry.id, this.time + (entry.cooldown || T.LINE_COOLDOWN));
    if (castId) this._cdVoice.set(castId, this.time + ((cast && cast.cooldown) || T.VOICE_COOLDOWN));
    const sid = opts.speakerId || castId;
    if (sid) this._cdSpeaker.set(sid, this.time + T.SPEAKER_COOLDOWN);
    this._remember(cat, entry.id);
    this.stats.said++;

    this._caption(handle, place);
    if (this.hasAudio) this._speak(handle, place, cast);
    else this.stats.captions++;

    return handle;
  }

  /**
   * Which active line (if any) may be thrown away to make room for `priority`.
   * Strictly lower priority only, oldest-started first — so a police warning
   * interrupts idle chatter but two dispatchers never cut each other off, and
   * the cap can never be exceeded by "just this once".
   */
  _evictionTarget(priority) {
    let best = null;
    for (const h of this._active) {
      if (h.priority >= priority) continue;
      if (!best || h.startedAt < best.startedAt) best = h;
    }
    return best;
  }

  /**
   * Weighted pick with recency suppression. Weight is:
   *   0                       if the line is inside its per-line cooldown
   *   base * RECENT_PENALTY   if it is in the category's recent ring
   *   base * 1.35             if it matches the requested cast (keeps a voice
   *                           saying lines written for it)
   * If everything is on cooldown we return null rather than repeating: silence
   * is a better failure than a parrot.
   */
  _pick(cat, list, castId, force) {
    const T = this.T;
    const recent = this._recent.get(cat);
    let total = 0;
    // Reused scratch array: `_pick` runs inside a crowd loop and a fresh array
    // per call is measurable GC churn at 60 Hz.
    if (!this._w || this._w.length < list.length) this._w = new Float64Array(Math.max(16, list.length * 2));
    const w = this._w;

    for (let i = 0; i < list.length; i++) {
      const e = list[i];
      let x = e.weight;
      if (!force && (this._cdLine.get(e.id) || 0) > this.time) x = 0;
      else {
        if (recent && recent.indexOf(e.id) >= 0) x *= T.RECENT_PENALTY;
        if (castId && e.cast && e.cast !== castId) x *= 0.25;  // wrong mouth
        else if (castId && e.cast === castId) x *= 1.35;
      }
      w[i] = x;
      total += x;
    }
    if (total <= 0) return null;

    let r = this.rng() * total;
    for (let i = 0; i < list.length; i++) {
      r -= w[i];
      if (r <= 0) return list[i];
    }
    return list[list.length - 1];
  }

  _remember(cat, id) {
    let ring = this._recent.get(cat);
    if (!ring) { ring = []; this._recent.set(cat, ring); }
    ring.push(id);
    while (ring.length > this.T.RECENT_MEMORY) ring.shift();
  }

  /* -------------------------------------------------------- captions --- */

  /**
   * Spec: "Voice captions appear only for nearby/important dialogue and can be
   * disabled." Note this runs BEFORE the audio path and does not depend on it:
   * captions are the product when there is no voice pack.
   */
  _caption(handle, place) {
    if (!this.subtitles || !this.onCaption) return;
    if (place && handle.priority < VOICE_PRIORITY.IMPORTANT) {
      const capRange = Math.max(this.T.MIN_AUDIBLE * 0.75, place.half * this.T.CAPTION_MULT);
      if (place.d > capRange) return;   // audible but off-screen: no subtitle
    }
    handle.captioned = true;
    // Fire-and-forget with a ttl. The HUD owns its own expiry — a UI that waits
    // for an "end" event from the audio layer shows a stuck caption forever the
    // first time a decode fails.
    try {
      this.onCaption({
        id: handle.id,
        text: handle.text,
        castId: handle.castId,
        castName: handle.castName,
        // Speaker colour for the subtitle. The HUD must show the NAME too:
        // colour is never the only signal (spec section 6, and voicelines.js
        // says the same about its own `color` field).
        color: handle.color,
        category: handle.category,
        priority: handle.priority,
        distance: handle.distance,
        ttl: handle.ttl,
        spoken: this.hasAudio,
      });
    } catch (err) {
      // A throwing HUD callback must not take the voice system down with it.
      if (typeof console !== 'undefined' && console.warn) console.warn('[voice] onCaption threw', err);
    }
  }

  /* -------------------------------------------------------- playback --- */

  /** Kick off async load + play. The slot is ALREADY reserved by `say()`. */
  _speak(handle, place, cast) {
    const gen = handle.gen;
    this._buffer(handle.id).then((buf) => {
      // Four ways this can be stale by the time the buffer lands: match ended,
      // the handle was evicted, it expired on its estimated ttl, or the player
      // muted. All of them must NOT produce sound.
      if (!buf || gen !== this._gen || !this._active.includes(handle) || this._muted) return;
      this._start(handle, buf, place, cast);
    }).catch(() => { /* _buffer already accounted for it */ });
  }

  _start(handle, buf, place, cast) {
    const ctx = this.ctx;
    let src, g, panner = null;
    try {
      src = ctx.createBufferSource();
      src.buffer = buf;
      g = ctx.createGain();
      const dist = place ? place.gain : 1;
      g.gain.value = clamp(this._volume * (cast ? cast.gain : 1) * dist, 0, 1.5);

      if (ctx.createStereoPanner) {
        // StereoPannerNode is equal-power by definition and costs one node;
        // a full PannerNode would give distance/HRTF we deliberately do not
        // want — this camera is fixed-yaw and top-down, so an HRTF cone points
        // the wrong way and just makes speech muddy.
        panner = ctx.createStereoPanner();
        panner.pan.value = place ? place.pan : 0;
        src.connect(g); g.connect(panner);
        panner.connect(this.destination || ctx.destination);
      } else {
        src.connect(g);
        g.connect(this.destination || ctx.destination);   // ancient Safari: mono
      }

      handle.src = src;
      handle.nodes = [g, panner];
      handle.spoken = true;
      // Correct the reservation to the real length now that we know it. The
      // estimate is only used to hold the slot; drift between the two is what
      // makes captions and audio fall out of sync over a match.
      handle.endsAt = this.time + buf.duration + 0.05;
      src.onended = () => this._retire(handle);
      src.start();
      this.stats.played++;
    } catch (err) {
      // A dead/closed context throws here. Free the slot rather than leaking it.
      this._retire(handle);
    }
  }

  _retire(handle, evicted = false) {
    const i = this._active.indexOf(handle);
    if (i >= 0) this._active.splice(i, 1);
    if (evicted) this.stats.evicted++;
    const src = handle.src;
    handle.src = null;
    if (src) {
      try { src.onended = null; src.stop(); } catch (err) { /* already ended */ }
      try { src.disconnect(); } catch (err) { /* noop */ }
    }
    if (handle.nodes) {
      for (const n of handle.nodes) { if (n) { try { n.disconnect(); } catch (err) { /* noop */ } } }
      handle.nodes = null;
    }
  }

  _stopSources() {
    for (let i = this._active.length - 1; i >= 0; i--) {
      const h = this._active[i];
      const src = h.src;
      h.src = null;
      if (src) {
        try { src.onended = null; src.stop(); } catch (err) { /* noop */ }
        try { src.disconnect(); } catch (err) { /* noop */ }
      }
      if (h.nodes) {
        for (const n of h.nodes) { if (n) { try { n.disconnect(); } catch (err) { /* noop */ } } }
        h.nodes = null;
      }
    }
  }

  /* ----------------------------------------------------------- update --- */

  /**
   * Advance the clock, refill the burst bucket, retire finished lines, smooth
   * the duck. Call once per frame with the same dt the simulation uses.
   */
  update(dt) {
    const T = this.T;
    const d = Math.min(Math.max(Number(dt) || 0, 0), 0.25);  // clamp: alt-tab
    this.time += d;

    this._tokens = Math.min(T.BURST_CAPACITY, this._tokens + T.BURST_REFILL * d);

    for (let i = this._active.length - 1; i >= 0; i--) {
      const h = this._active[i];
      // Two retirement paths on purpose. A caption-only line has no `ended`
      // event at all, and a real source can lose its `ended` when the context
      // is suspended mid-line (tab switch) — that leaked slot is invisible and
      // permanent, so the estimated end + ZOMBIE_GRACE is the backstop.
      const dead = h.spoken ? this.time > h.endsAt + T.ZOMBIE_GRACE : this.time >= h.endsAt;
      if (dead) this._retire(h);
    }

    let target = 0;
    for (const h of this._active) {
      if (h.priority >= VOICE_PRIORITY.IMPORTANT) { target = T.DUCK_AMOUNT; break; }
    }
    // Exponential approach with separate attack/release time constants. The
    // 1-exp form is frame-rate independent; a plain lerp with a fixed factor
    // ducks twice as fast at 120 fps as at 60.
    const tau = target > this._duck ? T.DUCK_ATTACK : T.DUCK_RELEASE;
    this._duck += (target - this._duck) * (1 - Math.exp(-d / Math.max(0.01, tau)));
    if (this._duck < 1e-4) this._duck = 0;

    return this;
  }

  /* ------------------------------------------------------------- reset -- */

  /**
   * MUST be called on match end / restart / menu return. Kills every source,
   * clears every cooldown, wipes captions, and — critically — invalidates every
   * in-flight fetch and decode via the generation counter, so a line requested
   * one frame before the match ended cannot start speaking into the next one.
   */
  stopAll() {
    this._gen++;
    this._stopSources();
    this._active.length = 0;
    this._lastStart = -1e6;
    this._tokens = this.T.BURST_CAPACITY;
    this._cdVoice.clear();
    this._cdSpeaker.clear();
    this._cdCategory.clear();
    this._cdLine.clear();
    this._recent.clear();
    this._duck = 0;
    if (this.onCaptionClear) {
      try { this.onCaptionClear(); } catch (err) { /* HUD's problem, not ours */ }
    }
    return this;
  }

  /** Release decoded audio too. Only for teardown — the cache is the point. */
  dispose() {
    this.stopAll();
    this._buffers.clear();
    this.manifest.clear();
    this.onCaption = null;
    this.onCaptionClear = null;
    return this;
  }
}

/* ======================================================== selftest ===== */

/**
 * Headless behaviour test. No WebAudio, no network, no DOM — it drives the
 * limiter through its internal clock, which is exactly why the clock is
 * internal. Run it from a console (`import('./src/audio/voice.js').then(m =>
 * m.__selftest().then(console.log))`) or from node with a stub voicelines.js.
 *
 * @returns {Promise<{pass: boolean, results: Array<{name:string, ok:boolean, info:string}>}>}
 */
export async function __selftest() {
  const results = [];
  const check = (name, ok, info = '') => { results.push({ name, ok: !!ok, info: String(info) }); };

  // Deterministic rng so a failure is reproducible.
  let seed = 0x2f6e2b1;
  const rng = () => {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };

  const LINES = {
    notice: [
      { id: 'n1', text: 'Uh, is that a sinkhole?', cast: 'tourist' },
      { id: 'n2', text: 'That road just left.', cast: 'local' },
      { id: 'n3', text: 'Nobody move.', cast: 'guard' },
      { id: 'n4', text: 'Are you seeing this?', cast: 'creator' },
    ],
    flee: [
      { id: 'f1', text: 'Nope, nope, nope!', cast: 'local' },
      { id: 'f2', text: 'Go, go, go!', cast: 'tourist' },
    ],
    police_warning: [
      { id: 'p1', text: 'Please move away from the plaza.', cast: 'dispatch' },
    ],
    CAST: {
      tourist: { name: 'Amused Tourist' },
      local: { name: 'Worried Local' },
      guard: { name: 'Security Guard' },
      creator: { name: 'Streamer' },
      dispatch: { name: 'City Dispatch' },
    },
  };

  const mk = (over = {}) => {
    const caps = [];
    const vs = new VoiceSystem({
      rng,
      lines: LINES,
      getListener: () => ({ x: 0, z: 0, radius: 4 }),
      onCaption: (c) => caps.push(c),
      ...over,
    });
    vs.captions = caps;
    return vs;
  };

  /* 1 — concurrency cap is never exceeded, even under force. ------------- */
  {
    const vs = mk();
    let peak = 0, over = 0;
    for (let i = 0; i < 200; i++) {
      vs.say('notice', { x: 1, z: 1, force: true, speakerId: `npc${i}` });
      peak = Math.max(peak, vs.activeCount);
      if (vs.activeCount > VOICE_TUNING.MAX_CONCURRENT) over++;
      if (i % 7 === 0) { vs.update(0.05); if (vs.activeCount > VOICE_TUNING.MAX_CONCURRENT) over++; }
    }
    check('concurrency cap never exceeded (forced spam)', over === 0 && peak <= VOICE_TUNING.MAX_CONCURRENT,
      `peak=${peak} violations=${over}`);
    // A forced low-priority line must NOT evict a peer of equal priority, so
    // the flood above should have produced few evictions, not 197 of them.
    check('equal priority does not evict', vs.stats.evicted === 0, `evicted=${vs.stats.evicted}`);
  }

  /* 2 — high priority evicts, still capped. ------------------------------ */
  {
    const vs = mk();
    for (let i = 0; i < 3; i++) {
      vs.say('notice', { x: 1, z: 1, force: true, speakerId: `a${i}` });
    }
    const before = vs.activeCount;
    const h = vs.say('police_warning', { priority: VOICE_PRIORITY.CRITICAL, force: true });
    check('critical line preempts chatter within the cap',
      !!h && before === 3 && vs.activeCount === 3 && vs.stats.evicted === 1,
      `active=${vs.activeCount} evicted=${vs.stats.evicted}`);
  }

  /* 3 — cooldowns honoured (category, voice, line), and each one in
         isolation: a test that passes because a DIFFERENT gate fired proves
         nothing, so every step below is placed past the previous gate's
         window and the control case is asserted alongside the blocked one. -- */
  {
    const vs = mk();
    const first = vs.say('notice', { x: 0, z: 0, castId: 'tourist', speakerId: 'ped7' });
    check('a first line speaks', !!first);

    // Two frames, not one update(0.5): update() clamps dt to 0.25 s (the
    // alt-tab guard), so a single big step silently lands at t=0.25 — still
    // inside MIN_START_GAP, and the assertion below would then be passing on
    // the wrong gate entirely. Hence also asserting the cutCooldown counter.
    vs.update(0.25); vs.update(0.25);                 // t=0.5, past the 0.42 gap
    const instant = vs.say('notice', { x: 0, z: 0, castId: 'local', speakerId: 'ped9' });
    check('per-category cooldown blocks an instant repeat',
      instant === null && vs.stats.cutCooldown === 1 && vs.stats.cutGap === 0,
      `cutCooldown=${vs.stats.cutCooldown} cutGap=${vs.stats.cutGap}`);

    // t = 2.0 s: category window (1.6) is over, voice window (5.0) is not.
    for (let i = 0; i < 30; i++) vs.update(0.05);
    const sameCast = vs.say('notice', { x: 0, z: 0, castId: 'tourist', speakerId: 'ped9' });
    check('per-voice cooldown still blocks the same cast at t=2s',
      sameCast === null, `t=${vs.time.toFixed(2)}`);
    // Control: a DIFFERENT cast at the same instant must get through, which is
    // what proves the block above was the voice cooldown and nothing else.
    const otherCast = vs.say('notice', { x: 0, z: 0, castId: 'local', speakerId: 'ped11' });
    check('a different cast speaks at the same instant', !!otherCast);

    // t > 5 s: the tourist is free again.
    for (let i = 0; i < 120; i++) vs.update(0.05);
    const later = vs.say('notice', { x: 0, z: 0, castId: 'tourist', speakerId: 'ped13' });
    check('voice cooldown releases after its window', !!later, `t=${vs.time.toFixed(1)}`);

    // Per-line: everything said so far is inside LINE_COOLDOWN (14 s), so the
    // pick must have avoided all of them.
    const used = [first, otherCast].filter(Boolean).map((h) => h.id);
    check('per-line cooldown steers away from lines already used',
      !!later && used.indexOf(later.id) < 0, `${used.join(',')} -> ${later && later.id}`);
  }

  /* 4 — burst damper, isolated from the other gates. --------------------- */
  {
    // Every other cooldown is zeroed so the bucket is the ONLY thing limiting
    // the crowd; otherwise this test would really be testing CATEGORY_COOLDOWN.
    const vs = mk({ tuning: {
      CATEGORY_COOLDOWN: 0, VOICE_COOLDOWN: 0, SPEAKER_COOLDOWN: 0,
      LINE_COOLDOWN: 0, MIN_START_GAP: 0,
    } });
    let spoken = 0;
    // 10 seconds of a panicking crowd: 6 NPCs try every frame, 600 frames.
    for (let f = 0; f < 600; f++) {
      for (let i = 0; i < 6; i++) if (vs.say('flee', { x: 2, z: 2, speakerId: `c${f}_${i}` })) spoken++;
      vs.update(1 / 60);
    }
    // Bucket budget over 10 s = capacity 4 + 0.55/s * 10 = 9.5 starts.
    const budget = VOICE_TUNING.BURST_CAPACITY + VOICE_TUNING.BURST_REFILL * 10;
    check('burst damper holds a 3600-attempt panic to the bucket budget',
      spoken <= Math.ceil(budget) + 1, `spoken=${spoken} budget=${budget}`);
    // The concurrency cap alone would have allowed roughly 3 / 1.7 s ≈ 17 in
    // the same window, so this also proves the damper — not the cap — is what
    // is binding. Without it the crowd would be twice as loud.
    check('burst damper is the binding constraint, not the cap', spoken < 15, `spoken=${spoken}`);
    check('burst damper does not silence the crowd', spoken >= 5, `spoken=${spoken}`);
  }

  /* 5 — distance culling: far NPCs never even pick a line. --------------- */
  {
    const vs = mk();
    const far = vs.say('notice', { x: 5000, z: 5000, speakerId: 'far' });
    check('far NPC is culled before selection', far === null && vs.stats.cutDistance === 1,
      `cutDistance=${vs.stats.cutDistance}`);
    // An IMPORTANT line ignores distance — dispatch is heard citywide.
    const dispatch = vs.say('police_warning', { x: 5000, z: 5000, priority: VOICE_PRIORITY.IMPORTANT });
    check('important line ignores the distance cut', !!dispatch);
  }

  /* 6 — weighted variation: no single line dominates. -------------------- */
  {
    const vs = mk();
    const seen = new Set();
    for (let i = 0; i < 40; i++) {
      const h = vs.say('notice', { x: 0, z: 0, force: true, speakerId: `v${i}` });
      if (h) seen.add(h.id);
      vs.update(0.5);
    }
    check('weighted selection uses more than one line', seen.size >= 3, `distinct=${seen.size}`);
  }

  /* 7 — graceful degradation when load() fails. -------------------------- */
  {
    const vs = mk();
    const realFetch = globalThis.fetch;
    try {
      globalThis.fetch = async () => { throw new Error('offline'); };
      const ok = await vs.load('/vo/manifest.json');
      check('load() failure resolves false, never throws', ok === false);
      check('mode falls back to captions', vs.mode === 'captions', vs.mode);
      const h = vs.say('notice', { x: 0, z: 0, force: true, speakerId: 'x' });
      check('say() still works with zero audio assets', !!h && vs.captions.length === 1,
        `captions=${vs.captions.length}`);
      check('caption carries text and ttl',
        !!vs.captions[0] && !!vs.captions[0].text && vs.captions[0].ttl > 0);

      // A 404 that returns HTML instead of JSON is the common dev-server case.
      globalThis.fetch = async () => ({ ok: true, status: 200, json: async () => { throw new Error('not json'); } });
      const ok2 = await vs.load('/vo/manifest.json');
      check('html-instead-of-json manifest degrades quietly', ok2 === false && vs.mode === 'captions');
    } finally {
      if (realFetch) globalThis.fetch = realFetch; else delete globalThis.fetch;
    }
  }

  /* 8 — subtitles toggle. ------------------------------------------------ */
  {
    const vs = mk();
    vs.setSubtitles(false);
    vs.say('notice', { x: 0, z: 0, force: true, speakerId: 'q' });
    check('subtitles off suppresses captions', vs.captions.length === 0);
  }

  /* 9 — stopAll leaves nothing alive and nothing can revive. ------------- */
  {
    const vs = mk();
    let cleared = 0;
    vs.onCaptionClear = () => { cleared++; };
    for (let i = 0; i < 3; i++) vs.say('notice', { x: 0, z: 0, force: true, speakerId: `s${i}` });
    const genBefore = vs._gen;
    const before = vs.activeCount;
    vs.stopAll();
    check('stopAll leaves zero active', before === 3 && vs.activeCount === 0, `before=${before}`);
    check('stopAll clears captions in the HUD', cleared === 1);
    check('stopAll invalidates in-flight async work', vs._gen === genBefore + 1);
    check('stopAll clears cooldowns and duck', vs._cdVoice.size === 0 && vs.duckAmount === 0);
    // And the very next frame is immediately speakable — a restart must not
    // inherit the previous match's gap.
    const after = vs.say('notice', { x: 0, z: 0, speakerId: 'fresh' });
    check('a fresh match can speak immediately after stopAll', !!after);
  }

  /* 10 — ducking rises for important lines and returns to zero. ---------- */
  {
    const vs = mk();
    vs.say('police_warning', { priority: VOICE_PRIORITY.IMPORTANT, force: true });
    for (let i = 0; i < 10; i++) vs.update(0.05);
    const peak = vs.duckAmount;
    for (let i = 0; i < 200; i++) vs.update(0.05);
    check('duckAmount rises while an important line plays', peak > 0.05, `peak=${peak.toFixed(3)}`);
    check('duckAmount returns to zero afterwards', vs.duckAmount === 0, `now=${vs.duckAmount}`);
  }

  /* 11 — slots are released by the clock alone (no WebAudio 'ended'). ---- */
  {
    const vs = mk();
    for (let i = 0; i < 3; i++) vs.say('notice', { x: 0, z: 0, force: true, speakerId: `z${i}` });
    for (let i = 0; i < 200; i++) vs.update(0.05);
    check('caption-only lines retire on the internal clock', vs.activeCount === 0, `active=${vs.activeCount}`);
  }

  /* 12 — the library adapter survives the shapes the data file may take. -- */
  {
    const table = { notice: ['one', 'two'] };
    // The likely real shape: a named export plus a default that IS that export.
    const vs = mk({ lines: { LINES: table, default: table, CAST: { a: { name: 'A' } } } });
    check('adapter does not double-register an aliased default export',
      vs.lines.get('notice') && vs.lines.get('notice').length === 2,
      `n=${vs.lines.get('notice') && vs.lines.get('notice').length}`);
    check('adapter reads cast profiles', vs.casts.has('a'));

    // Flat array shape.
    const vs2 = mk({ lines: { ALL: [{ category: 'flee', text: 'run' }] } });
    check('adapter reads the flat-array shape', !!vs2.lines.get('flee'));

    // Unrecognisable data must not crash and must not leave the game mute.
    const vs3 = mk({ lines: { nothing: 42 } });
    check('unusable line file falls back to the emergency bank',
      vs3.usingFallbackLines && !!vs3.say('notice', { x: 0, z: 0 }));
  }

  /* 13 — a manifest that loads but has no context to play it. ------------ */
  {
    const vs = mk();                                   // no audioCtx in deps
    const realFetch = globalThis.fetch;
    try {
      globalThis.fetch = async () => ({
        ok: true, status: 200,
        json: async () => ({ assets: {
          n1: 'n1.webm',                       // sibling of the manifest
          n2: '/static/n2.webm',               // root-absolute, verbatim
          n3: { url: 'https://cdn.test/n3.webm', seconds: 2.75 },
        } }),
      });
      const ok = await vs.load('http://localhost/vo/manifest.json');
      check('manifest without an AudioContext reports captions, not audio',
        ok === false && vs.mode === 'captions' && vs.manifest.size === 3,
        `mode=${vs.mode} size=${vs.manifest.size}`);
      check('relative asset urls resolve against the manifest url',
        vs.manifest.get('n1') === 'http://localhost/vo/n1.webm', vs.manifest.get('n1'));
      check('root-absolute and cdn urls are taken verbatim',
        vs.manifest.get('n2') === '/static/n2.webm'
        && vs.manifest.get('n3') === 'https://cdn.test/n3.webm',
        `${vs.manifest.get('n2')} | ${vs.manifest.get('n3')}`);
      check('declared durations are used for the slot reservation',
        vs._durations && vs._durations.get('n3') === 2.75);

      // The real generator's manifest, verbatim in shape.
      globalThis.fetch = async () => ({ ok: true, status: 200, json: async () => ({
        version: 1, pipeline: { msExact: true }, counts: { lines: 1 },
        lines: { 'notice-mina-sinkhole': { url: '/audio/voice/notice-mina-sinkhole.mp3', ms: 1420, cast: 'mina-sol' } },
      }) });
      const vs2 = mk();
      await vs2.load('/audio/voice/manifest.json');
      check('generator manifest: lines{} table, /-absolute url, ms duration',
        vs2.manifest.get('notice-mina-sinkhole') === '/audio/voice/notice-mina-sinkhole.mp3'
        && vs2._durations.get('notice-mina-sinkhole') === 1.42,
        `${vs2.manifest.get('notice-mina-sinkhole')} @ ${vs2._durations && vs2._durations.get('notice-mina-sinkhole')}`);

      // The boot order the game actually uses: manifest first, context later.
      vs._buffers.set('n1', 'missing');          // verdict reached with no ctx
      vs.attachContext({ fake: true });
      check('attachContext promotes a parked manifest to audio mode',
        vs.mode === 'audio' && vs._buffers.size === 0, vs.mode);
    } finally {
      if (realFetch) globalThis.fetch = realFetch; else delete globalThis.fetch;
    }
  }

  /* 14 — the DOCUMENTED voicelines.js api, which is the path that actually
         runs in the game. Shaped exactly like the real module: frozen rows
         from linesFor(), CAST as an array, CATEGORY_META priorities 1..4. ---- */
  {
    const row = (id, cast, text, cooldown, category) =>
      Object.freeze({ id, cast, text, category, weight: 1, cooldown });
    const notice = Object.freeze([row('n-1', 'mina', 'Uh, a sinkhole?', 25, 'notice')]);
    const police = Object.freeze([row('p-1', 'mina', 'Move away, please.', 35, 'policeWarning')]);
    const lib = {
      CATEGORIES: Object.freeze(['notice', 'policeWarning']),
      CATEGORY_META: {
        notice: { label: 'Notice', defaultCooldown: 25, priority: 1 },
        policeWarning: { label: 'Response warning', defaultCooldown: 35, priority: 4 },
      },
      CAST: [{ id: 'mina', displayName: 'Mina Sol', color: '#ffd166', cooldown: 9 }],
      linesFor: (c) => (c === 'notice' ? notice : c === 'policeWarning' ? police : []),
    };
    const vs = mk({ lines: lib });
    check('documented api binds without the shape prober',
      !vs.usingFallbackLines && vs.lines.get('notice').length === 1);
    check('cast array is read (name, colour, cooldown)',
      vs.casts.get('mina') && vs.casts.get('mina').name === 'Mina Sol'
      && vs.casts.get('mina').color === '#ffd166' && vs.casts.get('mina').cooldown === 9);
    check('CATEGORY_META priority 1..4 maps onto VOICE_PRIORITY 0..3',
      vs.categoryMeta.get('notice').priority === VOICE_PRIORITY.CHATTER
      && vs.categoryMeta.get('policeWarning').priority === VOICE_PRIORITY.CRITICAL,
      `notice=${vs.categoryMeta.get('notice').priority} police=${vs.categoryMeta.get('policeWarning').priority}`);

    // The corpus's 9 s voice cooldown must beat VOICE_TUNING's 5 s default.
    const first = vs.say('notice', { x: 0, z: 0 });
    check('a corpus line speaks and carries its speaker to the caption',
      !!first && vs.captions[0] && vs.captions[0].castName === 'Mina Sol'
      && vs.captions[0].color === '#ffd166');
    for (let i = 0; i < 24; i++) vs.update(0.25);          // t = 6 s
    const tooSoon = vs.say('policeWarning', { priority: VOICE_PRIORITY.CRITICAL });
    check('per-cast cooldown from the corpus (9s) outlasts the 5s default',
      tooSoon === null, `t=${vs.time.toFixed(1)}`);
    for (let i = 0; i < 20; i++) vs.update(0.25);          // t = 11 s
    check('the same voice speaks again once its own cooldown expires',
      !!vs.say('policeWarning', { priority: VOICE_PRIORITY.CRITICAL }), `t=${vs.time.toFixed(1)}`);
    // ...but the 25 s line lockout still holds, so 'notice' stays silent.
    check('per-line cooldown from the corpus (25s) outlasts the 14s default',
      vs.say('notice', { x: 0, z: 0 }) === null, `t=${vs.time.toFixed(1)}`);
    check('the corpus\'s frozen rows were copied, not mutated',
      Object.isFrozen(notice[0]) && notice[0].index === undefined);
  }

  /* 15 — REGRESSION GUARD for the bug class that nearly shipped: this module
         binding its own import. Every other case above uses `deps.lines`, so
         none of them would notice voicelines.js changing shape — the game
         would just quietly run on the two-line emergency bank. Skipped when
         the sibling file is a stub (a bundler-less node run). ---------------- */
  {
    const hasApi = typeof LINE_LIB.linesFor === 'function' && Array.isArray(LINE_LIB.CATEGORIES);
    const vs = new VoiceSystem({ rng, getListener: () => ({ x: 0, z: 0, radius: 4 }) });
    let n = 0;
    for (const l of vs.lines.values()) n += l.length;
    check('the imported corpus binds for real (skipped if it is a stub)',
      !hasApi || (!vs.usingFallbackLines && n >= 20 && vs.casts.size >= 3 && vs.categoryMeta.size >= 3),
      `api=${hasApi} categories=${vs.lines.size} lines=${n} casts=${vs.casts.size}`);
    check('every bound line has an id, text and a known category',
      [...vs.lines.entries()].every(([cat, l]) => l.every((e) => e.id && e.text && e.category === cat)));
  }

  const pass = results.every((r) => r.ok);
  return { pass, results, failed: results.filter((r) => !r.ok).map((r) => `${r.name} :: ${r.info}`) };
}

// Attached as a static too, so a console session that only grabbed the class
// can still run it.
VoiceSystem.__selftest = __selftest;

export default VoiceSystem;
